Iter13
vvv9912/ya-go-musthave-metrics-tpl pull request #14
Opened 2024-01-27 12:40 UTC by vvv9912

2024-01-29 09:18 UTC, tmvrus requested changes
- убрать весь закоменченый код
- починить тесты которые закоменчены
-

2024-01-29 09:18 UTC, tmvrus commented on cmd/server/main_test.go
> +	//counter := storage.NewCounterStorage()
оставлять закоментированный код это дурной тон, это усложняет чтение проекта

2024-01-29 09:18 UTC, tmvrus commented on internal/Agent/server/server.go
> +		fmt.Println(err)
fmt для логирования дургой тон

2024-01-29 09:18 UTC, tmvrus commented on internal/Server/handler/handler.go
> +		http.Error(res, "Failed to ping database", http.StatusInternalServerError)
тут return потерялся

2024-01-29 09:18 UTC, tmvrus commented on internal/Server/store/postgresql/repo.go
> +	defer stmt2.Close()
stmt можно было назвать пооригинальней
stmtCounter
stmtGauge
и создавать их можно один раз, при создание экземпляра Database

2024-01-29 09:18 UTC, tmvrus commented on internal/Server/store/postgresql/repo.go
> +	_, err := tx.ExecContext(ctx, "INSERT INTO GaugeMetrics (key, val) VALUES ($1, $2) ON CONFLICT (key) DO UPDATE SET val = $2;", key, val)
тут дублирование запроса который можно было переиспользовать

2024-01-29 09:18 UTC, tmvrus commented on internal/Server/store/postgresql/store.go
> +}
зачем тут транзакция если запрос всего один?

2024-01-29 09:18 UTC, tmvrus commented on internal/Server/store/postgresql/store.go
> +}
тот же самый вопрос

2024-01-29 09:18 UTC, tmvrus commented on internal/Server/handler/handler.go
> +	if (store2) == (*postgresql.Database)(nil) {
в каком месте курсе рекомендуют такие подходы?

2024-02-05 18:54 UTC, tmvrus requested changes
тесты починить
комментарии убрать

2024-02-05 18:54 UTC, tmvrus commented on cmd/server/flags.go
> +	//postgres://postgres:postgres@localhost:5432/postgres"
грязьненько

2024-02-05 18:54 UTC, tmvrus commented on cmd/server/main.go
> +			logger.Log.Panic("error up counter", zap.Error(err))
после вызова .Panic выполнение программы прекращается, возвращать после этого ошибку нет никакого смысла, потому что до нее выполнение никогда не дойдет

2024-02-05 18:54 UTC, tmvrus commented on cmd/server/main_test.go
>  }
грязьненько

2024-02-05 18:54 UTC, tmvrus commented on internal/Agent/notifier/notifier.go
вот тут в двух местах - ошибка проверяется и логируется, но код продолжает выполнятся, так будто никакой ошибки не было

2024-02-05 18:54 UTC, tmvrus commented on internal/Agent/notifier/notifier.go
> +				log.Println(err)
return?

2024-02-05 18:54 UTC, tmvrus commented on internal/Server/handler/handler.go
> +	if (store2) == (*postgresql.Database)(nil) {
что тут происходит ?
мы же обсужадали это

2024-02-05 18:54 UTC, tmvrus commented on internal/Server/handler/handler_test.go
> +	//jsonforTestMetric, err := json.Marshal(forTestMetric)
грязьненько

2024-02-05 18:54 UTC, tmvrus commented on internal/Server/server/server_test.go
> +	//type args struct {
грязьненько

2024-02-05 20:31 UTC, vvv9912 commented on cmd/server/flags.go
> +	//postgres://postgres:postgres@localhost:5432/postgres"
упс,про исправление тестов забыл)

2024-02-05 20:33 UTC, vvv9912 commented on internal/Agent/notifier/notifier.go
я просто не понимаю зачем возвращать ошибку, если нужно продолжать  отправлять запросы же, а так весь сервис упадет

2024-02-05 20:34 UTC, vvv9912 commented on internal/Server/handler/handler.go
> +	if (store2) == (*postgresql.Database)(nil) {
я не то запушил..

2024-02-06 12:17 UTC, vvv9912 commented on internal/Server/store/postgresql/store.go
> +}
Оставил транзакцию, так как использую ф-цию при добавлении батчей в бд

2024-02-06 20:16 UTC, tmvrus approved these changes
тесты надо чинить, а не комментировать

2024-02-06 20:16 UTC, tmvrus commented on internal/Agent/notifier/notifier.go
> -					//fmt.Println(err)
тут можно было хотя бы логировать ошибку, а так никто и не узнает что что-то сломалось

2024-02-07 19:15 UTC, merged