Iter5
vvv9912/ya-go-musthave-metrics-tpl pull request #5
Opened 2023-12-12 15:51 UTC by vvv9912

2023-12-13 21:01 UTC, tmvrus reviewed
ошибки при запуске, не используются значения по умолчанию?
```
go run cmd/server/main.go
# command-line-arguments
cmd/server/main.go:11:2: undefined: parseFlags
cmd/server/main.go:23:28: undefined: URLserver
go run cmd/agent/main.go
# command-line-arguments
cmd/agent/main.go:13:2: undefined: parseFlags
cmd/agent/main.go:26:23: undefined: pollInterval
cmd/agent/main.go:27:33: undefined: reportInterval
cmd/agent/main.go:28:23: undefined: URLserver
cmd/agent/main.go:32:74: undefined: pollInterval
cmd/agent/main.go:32:130: undefined: reportInterval
cmd/agent/main.go:32:160: undefined: URLserver
```

2023-12-13 21:02 UTC, tmvrus reviewed
ошибки в автотестах
https://github.com/vvv9912/ya-go-musthave-metrics-tpl/actions/runs/7184465092/job/19565594479?pr=5#step:12:25

2023-12-15 17:00 UTC, tmvrus requested changes

2023-12-15 17:00 UTC, tmvrus commented on cmd/agent/flags.go
> +	//os.Setenv("POLL_INTERVAL", "7")
такой код усложняет чтение проекта, его лучше не оставлять

2023-12-15 17:00 UTC, tmvrus commented on cmd/agent/flags.go
> +			log.Panic(err)
тут используется  log.Panic и выше просто panic
лучше придерживаться единообразия в этом вопросе

2023-12-15 17:00 UTC, tmvrus commented on cmd/agent/flags.go
> +	_ = flag.Value(addr)
такие проверки обычно выносят из ф-й, что-то типа
```go
var _ flag.Value = new(NetAddress)
```

2023-12-15 17:00 UTC, tmvrus commented on cmd/agent/flags.go
> +			panic("лишний флаг:" + f.Name)
тут можно добавить вывод флагов которые ожидает приложение
```
flag.PrintDefaults()
```

2023-12-15 17:00 UTC, tmvrus commented on cmd/agent/main.go
> +	<-done
это можно просто заменить на 
```
<-ctx.Done()
```
смысла будет тот же самый, но работать не будет, поскольку context.Background() никогда не будет Done

2023-12-15 17:00 UTC, tmvrus commented on internal/Server/mw/mw.go
> +				return
если убрать этот return то ничего не изменится

2023-12-15 17:00 UTC, tmvrus commented on internal/Server/mw/mw.go
> +			err = m.CounterStorage.UpdateCounter(name, http.StatusNotFound) //Зачем добавлять значение метрики 404, если не найдено?. Без этого тест не проходит
вот это очень странно)

2023-12-15 17:00 UTC, tmvrus commented on internal/Server/server/server.go
> +		}
следует помнить, что ListenAndServe() всегда возвращает ошибку, просто одна из них означает что все хорошо, это будет http.ErrServerClosed

2023-12-15 17:00 UTC, tmvrus commented on cmd/server/main.go
> +	<-done
тут тоже самое что и в агенте

2023-12-15 17:00 UTC, tmvrus commented on internal/Agent/metrics/metrics.go
> +func (m *Metrics) UpdateMetricsGauge() *map[string]string {
в данном случае нет никакого смысла в том, что бы работать с map как с *map

2023-12-15 17:00 UTC, tmvrus commented on internal/Agent/notifier/notifier.go
> +		return nil, 0, err
так работать не будет, после вызова log.Fatal приложение аварийно завершится, и до return уже не дойдет

2023-12-15 17:00 UTC, tmvrus commented on internal/Agent/notifier/notifier.go
> +func (n *Notifier) SendNotification(ctx context.Context, gauge *map[string]string, counter uint64) error {
нет никакого смысла работать с map как с *map

2023-12-15 17:00 UTC, tmvrus commented on internal/Agent/notifier/notifier.go
> +				return //return err?
это return не влияет на ход работы программы и в соседней горутине тоже

2023-12-15 17:00 UTC, tmvrus commented on internal/Server/mw/mw.go
> +		m.Log.Println("Получения значения метрики из хранилища:", name, ":", val)
а зачем два раза логировать?

2023-12-15 17:00 UTC, tmvrus commented on internal/Server/mw/mw.go
> +		log.Println("Обновление значения метрики:", name, ":", value)
а зачем два раза логировать?

2023-12-15 17:00 UTC, tmvrus commented on cmd/server/main.go
> +		return err
так работать не будет, после вызова log.Fatal приложение аварийно завершится, и до return уже не дойдет

2023-12-15 17:00 UTC, tmvrus commented on internal/Server/server/server.go
> +	}
Если кто-то отменить контекст снаружи (ctx.Done) то управление перейдет на строку 59 и заблокируется, потому что канал ch никто уже не читает, надо или добавить к нему буфер или персмотреть концепцию.

2023-12-17 17:44 UTC, vvv9912 commented on cmd/agent/flags.go
> +	_ = flag.Value(addr)
Тогда и реализацию интерфейса нужно делать вне функции?

2023-12-18 08:11 UTC, tmvrus approved these changes

2023-12-18 15:18 UTC, tmvrus commented on cmd/agent/flags.go
> +	_ = flag.Value(addr)
да, обычно так и делают

2023-12-18 19:30 UTC, merged