Iter9
vvv9912/ya-go-musthave-metrics-tpl pull request #9
Opened 2024-01-08 15:28 UTC by vvv9912

2024-01-09 15:57 UTC, tmvrus requested changes
- убрать закоменченый код, засоряет проект
- разобраться с сообщениями об ошибках и статусами ответов

2024-01-09 15:57 UTC, tmvrus commented on internal/Server/fileutils/fileutils.go
> +//}
вот это прям очень некрасиво

2024-01-09 15:57 UTC, tmvrus commented on internal/Server/handler/handler.go
> +		http.Error(res, "Failed to read request body", http.StatusNotFound)
http.StatusNotFound возвращают когда запрошенный ресурс не найден, тут больше подойдет InternalError

2024-01-09 15:57 UTC, tmvrus commented on internal/Server/handler/handler.go
> +		logger.Log.Error("ошибка отправки метрик в файл", zap.Error(err))
тут пожалуй должен быть return

2024-01-09 15:57 UTC, tmvrus commented on internal/Server/handler/handler.go
> +	}
при таком подходе теряется сама ошибка и никто не узнает что случилось, это нужно хотя бы логировать

2024-01-09 15:57 UTC, tmvrus commented on internal/Server/handler/handler.go
> +		http.Error(res, "Failed to read request body", http.StatusNotFound)
- странное сообщение об ошибке
- странный статус код
- теряется оригинальная ошибка

2024-01-09 15:57 UTC, tmvrus commented on internal/Server/project/project.go
> +type Project struct {
максимально странное название для компонента, оно ничего не говорит о том, что внутри

2024-01-09 15:57 UTC, tmvrus commented on internal/Server/mw/mw.go
> +		_, supportContentType := acceptType[acceptContentType]
такая проверка будет работать не всегда, формат заголовка позволяет разные комбинации, или вообще `Accept: */*`
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept

2024-01-09 15:57 UTC, tmvrus commented on internal/Server/mw/mw.go
> +			if supportsGzip {
можно оставить только один if 
```go
if supportContentType && supportsGzip {
```

2024-01-09 15:57 UTC, tmvrus commented on internal/Server/mw/mw.go
> +		if req.Header.Get("Content-Type") != "application/json" {
"Content-Type" может содержать что-то типа
`Content-Type: application/json; charset=utf-8`
не стоит полагаться на строгое равенство

2024-01-09 15:57 UTC, tmvrus commented on cmd/server/main.go
> +			//return err
почему ошибка игнорируется, файл ведь может не быть например?

2024-01-09 15:57 UTC, tmvrus commented on internal/Server/fileutils/fileutils.go
> +	consumer, err := NewConsumer(fileName)
а зачем внутри консюмера создавать еще один точно такой же, что бы читать из того же самого файла?

2024-01-11 20:40 UTC, vvv9912 commented on cmd/server/main.go
> +			//return err
Думал, необязательно, тк в случае отсутствия создастся новый файл

2024-01-11 20:44 UTC, vvv9912 commented on internal/Server/fileutils/fileutils.go
> +	consumer, err := NewConsumer(fileName)
опечатался

2024-01-13 11:11 UTC, tmvrus commented on cmd/server/main.go
> +			//return err
У приложения, например, может не быть прав на директорию. И тогда файл не будет создан.

2024-01-13 11:25 UTC, tmvrus approved these changes
работа хорошая, но все еще есть путаница в http-кодах
если хочешь разобраться, приходи на 1-1 с этим PR

2024-01-13 11:25 UTC, tmvrus commented on internal/Agent/notifier/notifier.go
> +			}
тут есть ранее незамеченная проблема: код продолжит выполнятся в случае ошибки, так как логирование не меняет ходя исполнения программы. Судя по коду, рядом с логированием пропущен return

2024-01-13 11:25 UTC, tmvrus commented on internal/Agent/notifier/notifier.go
> +		}
тут похожая проблема

2024-01-13 11:25 UTC, tmvrus commented on internal/Agent/server/server.go
> +		fmt.Println(err)
во втором хорошо изложена тема логирования и различных пакетов для этого, использовать для логирования пакет fmt не самая лучшая идея, просто потому что он для этого не предназначен

2024-01-13 11:25 UTC, tmvrus commented on internal/Server/mw/mw.go
> +	return supportContent
эту ф-ю можно переписать короче:
```go
if acceptTypeReq == "*/*" {
  return true
}
for key := range acceptType {
	if strings.Contains(acceptTypeReq, key) {
            return true
	}
}
return false
```

2024-01-13 11:25 UTC, tmvrus commented on internal/Server/mw/mw.go
> +	return supportEncoding
тут тоже можно короче)

2024-01-14 16:22 UTC, vvv9912 commented on internal/Agent/notifier/notifier.go
> +			}
да, просто раньше код был меньше и не имело смысла писать return, а сейчас разросся и уже имеет. Но с другой стороны, там ниже отправление JSON, поэтому, наверное, имеет смысл изменить логику исполнения этой функции

2024-01-20 17:15 UTC, merged